### ISSUE TITLE
No metrics if node is offline

### ISSUE THREAD

**Issue by Charles226** [easy2stake/elrond#3]
We're utilising the script to populate a textfile and then running a cron job for the node exporter as recommended.  The script works fantastically to report on the listed metrics as it's running however when the node isn't running all metrics are blank.  Could you possible suggest a way to have a metric populated when the node isn't running so that we can trigger an alert from Prometheus ?

please let me know if that doesn't make any sense.

**Comment by easy2stake** [comment]
We can update the script to write a new metric when the node is offline.

I'd like to suggest a workaround also. Prometheus offers the possibility to report on missing metrics.

Say your metric is this one: erd_test_metric
Then write a rule like this: 
```sh
time() - max_over_time(timestamp(erd_test_metric)[24h:])
```
It will tell you what are the missing metrics in the past 24h. The normal graph looks like a sawtooth.
